# This file was generated by GoReleaser. DO NOT EDIT.
cask "portman" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/portman"],
        writable_paths: ["portman"], writable_base: :staged_path
  end

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "27927e365b08d825adcd35eee39e5d04adb83cfcf630576a585b7b5e0aaf4bf8"
      url "https://github.com/tasnimzotder/portman/releases/download/v#{version}/portman_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6973995e564bc50bd4f5661b464d41054a0729b15f1643a6cfaee5632f93e276"
      url "https://github.com/tasnimzotder/portman/releases/download/v#{version}/portman_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "portman"
  desc "See what's using your ports. Kill rogue processes. Wait for services."
  homepage "https://github.com/tasnimzotder/portman"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portman"

  # No zap stanza required
end
