# This file was generated by GoReleaser. DO NOT EDIT.
cask "portman" do
  name "portman"
  desc "See what's using your ports. Kill rogue processes. Wait for services."
  homepage "https://github.com/tasnimzotder/portman"
  version "0.0.1-beta.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portman"

  on_macos do
    on_intel do
      url "https://github.com/tasnimzotder/portman/releases/download/v#{version}/portman_#{version}_darwin_amd64.tar.gz"
      sha256 "283e3aa90d318ceaecd58f45532f08873e9da0fa1a44303fe96beecfaf1b3dc2"
    end
    on_arm do
      url "https://github.com/tasnimzotder/portman/releases/download/v#{version}/portman_#{version}_darwin_arm64.tar.gz"
      sha256 "f40412ab26c5122457d28070abf8f35c5e8bf3ef3a813417350ef787647acc74"
    end
  end

  # No zap stanza required
end
