# This file was generated by GoReleaser. DO NOT EDIT.
cask "portman" do
  name "portman"
  desc "See what's using your ports. Kill rogue processes. Wait for services."
  homepage "https://github.com/tasnimzotder/portman"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portman"

  on_macos do
    on_intel do
      url "https://github.com/tasnimzotder/portman/releases/download/v#{version}/portman_#{version}_darwin_amd64.tar.gz"
      sha256 "b68bd608fecfcce792156aa911cf170af3f6b735542f972fbe1beb1abdccd3a2"
    end
    on_arm do
      url "https://github.com/tasnimzotder/portman/releases/download/v#{version}/portman_#{version}_darwin_arm64.tar.gz"
      sha256 "a30f3782257d034752842da2445ae59a8cd01c340f777e494b3bd513f00df577"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portman"]
  end

  # No zap stanza required
end
